services:
  musical1c:
    image: musical1c
    build:
      context: .
      dockerfile: Musical1C/Dockerfile
    ports:
      - "5001:5001"
    environment:
      ConnectionStrings__Default: "Host=postgres;Database=musical1c;Username=postgres;Password=1111"
    depends_on:
      - postgres
      
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: musical1c
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  postgres-data:
